### ISSUE TITLE
sub identifier with embedded ":" fails auth if c2id is clustered

### ISSUE THREAD

**Issue by pakfur** [Connect2id/Server-Issues#1] opened 2015-07-07 22:11 UTC
Submitted by 

John Kline (jkline@riotgames.com)

If c2id is clustered the nimbus SubjectKey deserialization code throws an exception. The SubjectKey encodes the sub value with a number, ":" separated.  Embedded colons in the sub claim trigger the exception.

This error does not occur in singleton mode.

example subject: "urn:riot:pid:v1:UIOEURIOEHEKLFHEKLHK"

Example trace:
app_1     | 2015-07-07T21:52:20,379 DEBUG http-nio-8080-exec-8 CLIENT-REG - [OP5153] Provisioned and stored information for new client 5mh7q5prpwtt4
app_1     | 07-Jul-2015 21:52:20.744 ERROR [http-nio-8080-exec-24] <unknown>.<unknown> ISPN000136: Execution error
app_1     |  org.infinispan.remoting.RemoteException: ISPN000217: Received exception from ip-10-180-243-64-37054, see cause for remote stack trace
app_1     | 	at org.infinispan.remoting.transport.AbstractTransport.checkResponse(AbstractTransport.java:46)
app_1     | 	at org.infinispan.remoting.transport.jgroups.CommandAwareRpcDispatcher.processSingleCall(CommandAwareRpcDispatcher.java:442)
app_1     | 	at org.infinispan.remoting.transport.jgroups.CommandAwareRpcDispatcher.invokeRemoteCommand(CommandAwareRpcDispatcher.java:241)
app_1     | 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.invokeRemotely(JGroupsTransport.java:561)
app_1     | 	at org.infinispan.remoting.rpc.RpcManagerImpl.invokeRemotely(RpcManagerImpl.java:287)
app_1     | 	at org.infinispan.interceptors.distribution.BaseDistributionInterceptor.handleNonTxWriteCommand(BaseDistributionInterceptor.java:353)
app_1     | 	at org.infinispan.interceptors.distribution.NonTxDistributionInterceptor.visitPutKeyValueCommand(NonTxDistributionInterceptor.java:105)
app_1     | 	at org.infinispan.commands.write.PutKeyValueCommand.acceptVisitor(PutKeyValueCommand.java:71)
app_1     | 	at org.infinispan.interceptors.base.CommandInterceptor.invokeNextInterceptor(CommandInterceptor.java:97)
app_1     | 	at org.infinispan.interceptors.EntryWrappingInterceptor.invokeNextAndApplyChanges(EntryWrappingInterceptor.java:388)
app_1     | 	at org.infinispan.interceptors.EntryWrappingInterceptor.setSkipRemoteGetsAndInvokeNextForDataCommand(EntryWrappingInterceptor.java:453)
app_1     | 	at org.infinispan.interceptors.EntryWrappingInterceptor.visitPutKeyValueCommand(EntryWrappingInterceptor.java:195)
app_1     | 	at org.infinispan.commands.write.PutKeyValueCommand.acceptVisitor(PutKeyValueCommand.java:71)
app_1     | 	at org.infinispan.interceptors.base.CommandInterceptor.invokeNextInterceptor(CommandInterceptor.java:97)
app_1     | 	at org.infinispan.interceptors.locking.AbstractLockingInterceptor.visitNonTxDataWriteCommand(AbstractLockingInterceptor.java:86)
app_1     | 	at org.infinispan.interceptors.locking.NonTransactionalLockingInterceptor.visitDataWriteCommand(NonTransactionalLockingInterceptor.java:40)
app_1     | 	at org.infinispan.interceptors.locking.AbstractLockingInterceptor.visitPutKeyValueCommand(AbstractLockingInterceptor.java:55)
app_1     | 	at org.infinispan.commands.write.PutKeyValueCommand.acceptVisitor(PutKeyValueCommand.java:71)
app_1     | 	at org.infinispan.interceptors.base.CommandInterceptor.invokeNextInterceptor(CommandInterceptor.java:97)
app_1     | 	at org.infinispan.interceptors.base.CommandInterceptor.handleDefault(CommandInterceptor.java:111)
app_1     | 	at org.infinispan.commands.AbstractVisitor.visitPutKeyValueCommand(AbstractVisitor.java:44)
app_1     | 	at org.infinispan.commands.write.PutKeyValueCommand.acceptVisitor(PutKeyValueCommand.java:71)
app_1     | 	at org.infinispan.interceptors.base.CommandInterceptor.invokeNextInterceptor(CommandInterceptor.java:97)
app_1     | 	at org.infinispan.statetransfer.StateTransferInterceptor.handleNonTxWriteCommand(StateTransferInterceptor.java:317)
app_1     | 	at org.infinispan.statetransfer.StateTransferInterceptor.handleWriteCommand(StateTransferInterceptor.java:249)
app_1     | 	at org.infinispan.statetransfer.StateTransferInterceptor.visitPutKeyValueCommand(StateTransferInterceptor.java:108)
app_1     | 	at org.infinispan.commands.write.PutKeyValueCommand.acceptVisitor(PutKeyValueCommand.java:71)
app_1     | 	at org.infinispan.interceptors.base.CommandInterceptor.invokeNextInterceptor(CommandInterceptor.java:97)
app_1     | 	at org.infinispan.interceptors.CacheMgmtInterceptor.updateStoreStatistics(CacheMgmtInterceptor.java:191)
app_1     | 	at org.infinispan.interceptors.CacheMgmtInterceptor.visitPutKeyValueCommand(CacheMgmtInterceptor.java:177)
app_1     | 	at org.infinispan.commands.write.PutKeyValueCommand.acceptVisitor(PutKeyValueCommand.java:71)
app_1     | 	at org.infinispan.interceptors.base.CommandInterceptor.invokeNextInterceptor(CommandInterceptor.java:97)
app_1     | 	at org.infinispan.interceptors.InvocationContextInterceptor.handleAll(InvocationContextInterceptor.java:102)
app_1     | 	at org.infinispan.interceptors.InvocationContextInterceptor.handleDefault(InvocationContextInterceptor.java:71)
app_1     | 	at org.infinispan.commands.AbstractVisitor.visitPutKeyValueCommand(AbstractVisitor.java:44)
app_1     | 	at org.infinispan.commands.write.PutKeyValueCommand.acceptVisitor(PutKeyValueCommand.java:71)
app_1     | 	at org.infinispan.interceptors.InterceptorChain.invoke(InterceptorChain.java:336)
app_1     | 	at org.infinispan.cache.impl.CacheImpl.executeCommandAndCommitIfNeeded(CacheImpl.java:1617)
app_1     | 	at org.infinispan.cache.impl.CacheImpl.putIfAbsentInternal(CacheImpl.java:1122)
app_1     | 	at org.infinispan.cache.impl.CacheImpl.putIfAbsent(CacheImpl.java:1112)
app_1     | 	at org.infinispan.cache.impl.CacheImpl.putIfAbsent(CacheImpl.java:1717)
app_1     | 	at org.infinispan.cache.impl.CacheImpl.putIfAbsent(CacheImpl.java:283)
app_1     | 	at com.nimbusds.sessionstore.InfinispanSubjectSessionStore.registerSubject(InfinispanSubjectSessionStore.java:148)
app_1     | 	at com.nimbusds.sessionstore.InfinispanSubjectSessionStore.add(InfinispanSubjectSessionStore.java:264)
app_1     | 	at com.nimbusds.openid.connect.provider.authz.SubjectSessionManager.startNewSubjectSession(SubjectSessionManager.java:77)
app_1     | 	at com.nimbusds.openid.connect.provider.authz.AuthorizationHandler.submitSubjectSession(AuthorizationHandler.java:667)
app_1     | 	at com.nimbusds.openid.connect.provider.authz.AuthorizationSessionEndpoint.submitAdditionalData(AuthorizationSessionEndpoint.java:179)
app_1     | 	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
app_1     | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
app_1     | 	at java.lang.reflect.Method.invoke(Method.java:606)
app_1     | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
app_1     | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:164)
app_1     | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:181)
app_1     | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:158)
app_1     | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:101)
app_1     | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
app_1     | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
app_1     | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
app_1     | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:305)
app_1     | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
app_1     | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
app_1     | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
app_1     | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
app_1     | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
app_1     | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
app_1     | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288)
app_1     | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110)
app_1     | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:401)
app_1     | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
app_1     | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335)
app_1     | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:222)
app_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
app_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
app_1     | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
app_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
app_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
app_1     | 	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:208)
app_1     | 	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:274)
app_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
app_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
app_1     | 	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
app_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
app_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
app_1     | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
app_1     | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
app_1     | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
app_1     | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
app_1     | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
app_1     | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
app_1     | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:534)
app_1     | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081)
app_1     | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
app_1     | 	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
app_1     | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
app_1     | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
app_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
app_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
app_1     | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
app_1     | 	at java.lang.Thread.run(Thread.java:745)
app_1     | Caused by: org.infinispan.commons.CacheException: Problems invoking command.
app_1     | 	at org.infinispan.remoting.transport.jgroups.CommandAwareRpcDispatcher.handle(CommandAwareRpcDispatcher.java:318)
app_1     | 	at org.jgroups.blocks.RequestCorrelator.handleRequest(RequestCorrelator.java:460)
app_1     | 	at org.jgroups.blocks.RequestCorrelator.receiveMessage(RequestCorrelator.java:377)
app_1     | 	at org.jgroups.blocks.RequestCorrelator.receive(RequestCorrelator.java:250)
app_1     | 	at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.up(MessageDispatcher.java:675)
app_1     | 	at org.jgroups.JChannel.up(JChannel.java:739)
app_1     | 	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:1029)
app_1     | 	at org.jgroups.protocols.FRAG2.up(FRAG2.java:165)
app_1     | 	at org.jgroups.protocols.FlowControl.up(FlowControl.java:394)
app_1     | 	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:1042)
app_1     | 	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:234)
app_1     | 	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1064)
app_1     | 	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:779)
app_1     | 	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:426)
app_1     | 	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:652)
app_1     | 	at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:155)
app_1     | 	at org.jgroups.protocols.FD_ALL.up(FD_ALL.java:200)
app_1     | 	at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:297)
app_1     | 	at org.jgroups.protocols.MERGE3.up(MERGE3.java:288)
app_1     | 	at org.jgroups.protocols.Discovery.up(Discovery.java:291)
app_1     | 	at org.jgroups.protocols.TP.passMessageUp(TP.java:1577)
app_1     | 	at org.jgroups.protocols.TP$MyHandler.run(TP.java:1796)
app_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
app_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
app_1     | 	... 1 more
app_1     | Caused by: java.io.IOException: Invalid subject key
app_1     | 	at com.nimbusds.sessionstore.SubjectKeyExternalizer.readObject(SubjectKeyExternalizer.java:62)
app_1     | 	at com.nimbusds.sessionstore.SubjectKeyExternalizer.readObject(SubjectKeyExternalizer.java:16)
app_1     | 	at org.infinispan.marshall.core.ExternalizerTable$ExternalizerAdapter.readObject(ExternalizerTable.java:436)
app_1     | 	at org.infinispan.marshall.core.ExternalizerTable.readObject(ExternalizerTable.java:227)
app_1     | 	at org.infinispan.marshall.core.JBossMarshaller$ExternalizerTableProxy.readObject(JBossMarshaller.java:153)
app_1     | 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:354)
app_1     | 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:209)
app_1     | 	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
app_1     | 	at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readParameters(ReplicableCommandExternalizer.java:101)
app_1     | 	at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:84)
app_1     | 	at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:31)
app_1     | 	at org.infinispan.marshall.core.ExternalizerTable$ExternalizerAdapter.readObject(ExternalizerTable.java:436)
app_1     | 	at org.infinispan.marshall.core.ExternalizerTable.readObject(ExternalizerTable.java:227)
app_1     | 	at org.infinispan.marshall.core.JBossMarshaller$ExternalizerTableProxy.readObject(JBossMarshaller.java:153)
app_1     | 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:354)
app_1     | 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:209)
app_1     | 	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
app_1     | 	at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readParameters(ReplicableCommandExternalizer.java:101)
app_1     | 	at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:154)
app_1     | 	at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:65)
app_1     | 	at org.infinispan.marshall.core.ExternalizerTable$ExternalizerAdapter.readObject(ExternalizerTable.java:436)
app_1     | 	at org.infinispan.marshall.core.ExternalizerTable.readObject(ExternalizerTable.java:227)
app_1     | 	at org.infinispan.marshall.core.JBossMarshaller$ExternalizerTableProxy.readObject(JBossMarshaller.java:153)
app_1     | 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:354)
app_1     | 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:209)
app_1     | 	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
app_1     | 	at org.infinispan.commons.marshall.jboss.AbstractJBossMarshaller.objectFromObjectStream(AbstractJBossMarshaller.java:134)
app_1     | 	at org.infinispan.marshall.core.VersionAwareMarshaller.objectFromByteBuffer(VersionAwareMarshaller.java:101)
app_1     | 	at org.infinispan.commons.marshall.AbstractDelegatingMarshaller.objectFromByteBuffer(AbstractDelegatingMarshaller.java:80)
app_1     | 	at org.infinispan.remoting.transport.jgroups.MarshallerAdapter.objectFromBuffer(MarshallerAdapter.java:28)
app_1     | 	at org.infinispan.remoting.transport.jgroups.CommandAwareRpcDispatcher.handle(CommandAwareRpcDispatcher.java:298)
app_1     | 	... 24 more
app_1     |

**Comment by c2id-support** [comment] 2015-07-08 06:02
Thanks, the problem was reproduced and is now being worked on.

**Comment by c2id-support** [comment] 2015-07-08 06:24
The bug has been fixed by changing de-serialisation to support colons in the subject ID. The fix will be included in the next maintenance release of the server.

**Comment by c2id-support** [comment] 2015-07-08 09:42
The fix got included in today's 3.2.1 release:

http://connect2id.com/blog/connect2id-server-3.2.1

Thanks again for the detailed bug report, it helped us fix the issue very quickly.

**Closed by c2id-support** 2015-07-08 09:42 UTC
